### ISSUE TITLE
Unpack .qbttheme file?

### ISSUE THREAD

**Issue by delivey** [tatokis/qresExtract#1]
I'm having trouble unpacking a .qbttheme file, how do you do it using this sofware?

I am on Windows

**Comment by tatokis** [comment]
Is that a qbittorrent theme file?
If so I just searched for a random one and extracted it just fine.

```
$ ./qresExtract '/home/tatokis/Επιφάνεια εργασίας/style.qbtheme' /tmp/
/stylesheet.qss
$ ls /tmp/style/
style.qrc  stylesheet.qss
```

**Comment by delivey** [comment]
Yes, that is a qbittorrent theme file.
I am on Windows, let's say I have the .qbtheme file on my Desktop.
Do I write `./qresExtract '/C:/Users/MyUser/Desktop/style.qbtheme' /C:/Users/MyUser/Desktop/
/stylesheet.qss` ? because that doesn't seem to work.

**Comment by A-Sparowe** [comment]
> 
> 
> Yes, that is a qbittorrent theme file.
> I am on Windows, let's say I have the .qbtheme file on my Desktop.
> Do I write `./qresExtract '/C:/Users/MyUser/Desktop/style.qbtheme' /C:/Users/MyUser/Desktop/ /stylesheet.qss` ? because that doesn't seem to work.

+1 to this question. I've been pulling my hair out. Is this done with PowerShell or Command Prompt or GitBash or I have no clue honestly. I do have Git installed on my PC but I don't have QT.

**Comment by tatokis** [comment]
You need to compile it with either qt creator + msvc or msys2, to get an exe and run that.

Both are huge downloads, and a bit of a pain to set up, so I'll see if I can get an executable built that works and upload it.

**Comment by tatokis** [comment]
Get the latest release/7z archive from https://github.com/tatokis/qresExtract/releases/

Extract it, and drag and drop a file to qresExtract.exe

It will make a folder with the same name as the file you're trying to extract, inside the folder that file is in.
